# Generated by Django 3.1.4 on 2021-01-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='easymart_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brocher',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
