# Generated by Django 3.1.4 on 2021-01-12 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210112_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail_specification',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
