# Generated by Django 3.0 on 2021-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('IT', 'IT Product'), ('POS', 'POS Product')], default='', max_length=128),
        ),
    ]
