# Generated by Django 3.0 on 2021-03-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('tracking_code', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.BigIntegerField(default='')),
                ('estimate_time', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('IT', 'IT Product'), ('POS', 'POS Product')], default='', max_length=128)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
