# Generated by Django 3.0 on 2021-03-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
